version: "3.3"

services:
  zcs-dev:
    image: zimbra/zcs-dev:8.8.6.2ga
    depends_on:
      - solr
    environment:
      GITEMAIL: ${GITEMAIL}
      GITNAME: "${GITNAME}"
      SOLR_MODE: ${SOLR_MODE}
      SOLR_MEMORY: ${SOLR_MEMORY}
    entrypoint:
      - /zimbra/init
    volumes:
      - $REPO_DIR/slash-zimbra:/zimbra
      - $HOME_ZIMBRA:/home/zimbra:delegated
      - type: volume
        source: opt_zimbra
        target: /opt/zimbra
        volume:
          nocopy: false
    hostname: zcs-dev
    ports:
      - "2222:22"
      - "7071:7071"
      - "8143:143"
      - "8443:443"
      - "8993:993"
      - "9998:9998"
      - "9999:9999"
  zmc-zookeeper:
    image: zmc-zookeeper
    hostname: zookeeper-zcs
    env_file: .env
    networks:
      default:
        ipv4_address: 10.0.0.5
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    entrypoint: /opt/zookeeper/zk/entrypoint
    volumes:
      - $REPO_DIR/zk:/opt/zookeeper/zk:rw
      - zookeeper_data:/tmp/zookeeper:rw
  solr:
    image: zimbra/zm-solr-docker:7.2-20180315
    depends_on:
      - zmc-zookeeper
    hostname: solr
    env_file: .env
    networks:
      default:
        ipv4_address: 10.0.0.4
    entrypoint: /solr/entrypoint
    ports:
      - "8983:8983"
    volumes:
      - $REPO_DIR/solr:/solr:rw
      - idxvolume:/opt/solr/server/solr


volumes:
  opt_zimbra: {}
  idxvolume: {}
  zookeeper_data: {}
