version: "3.3"

services:
  zcs-dev:
    image: zimbra/zcs-dev:8.8.15ga
    env_file: .env
    entrypoint:
      - /zimbra/init
    volumes:
      - $REPO_DIR/slash-zimbra:/zimbra
      - $HOME_ZIMBRA:/home/zimbra
      - type: volume
        source: opt_zimbra
        target: /opt/zimbra
        volume:
          nocopy: false
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 32768
        hard: 32768
    container_name: zcs-dev
    domainname: test
    hostname: zcs-dev
    ports:
      - "2222:22"
      - "7071:7071"
      - "8143:143"
      - "9443:443"
      - "8993:993"
      - "9998:9998"
      - "9999:9999"
    networks:
      default:

networks:
  default:
    driver: bridge

volumes:
  opt_zimbra: {}
