version: "3.3"

services:
  zmc-mysql:
    image: "zimbra/zmc-mysql"
    hostname: "zmc-mysql"
    container_name: "zmc-mysql"
    volumes:
      - .:/code
    secrets:
      - mysql.password
    networks:
      default:
        ipv4_address: 10.0.0.5
    ports:
      - "7306:7306"
  zcs-dev:
    image: zimbra/zcs-dev:8.8.4ga
    depends_on:
      - solr
    env_file: .env
    container_name: zcs-dev
    hostname: zcs-dev
    domainname: test
    entrypoint:
      - /zimbra/init
    volumes:
      - $REPO_DIR/slash-zimbra:/zimbra
      - $HOME_ZIMBRA:/home/zimbra
      - blobvolume:/opt/zimbra/store
      - tmpvolume:/opt/zimbra/data/tmp
    container_name: zcs-dev
    domainname: test
    hostname: zcs-dev
    networks:
      default:
        ipv4_address: 10.0.0.3
    ports:
      - "2222:22"
      - "7071:7071"
      - "8143:143"
      - "8443:443"
      - "8993:993"
      - "9998:9998"
      - "9999:9999"
  solr:
    image: zimbra/zm-solr-docker
    container_name: solr
    env_file: .env
    networks:
      default:
        ipv4_address: 10.0.0.4
    entrypoint: /solr/entrypoint
    ports:
      - "8983:8983"
    volumes:
      - $REPO_DIR/solr:/solr

secrets:
  mysql.password:
    file: .secrets/mysql.password

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/24

volumes:
  blobvolume: {}
  tmpvolume: {}
