version: "3.3"

services:
  zcs-dev:
    image: zimbra/zcs-dev:8.8.8ga
    depends_on:
      - solr
    env_file: .env
    entrypoint:
      - /zimbra/init
    volumes:
      - $REPO_DIR/slash-zimbra:/zimbra
      - $HOME_ZIMBRA:/home/zimbra
      - type: volume
        source: opt_zimbra
        target: /opt/zimbra
        volume:
          nocopy: false

    container_name: zcs-dev
    domainname: test
    hostname: zcs-dev
    networks:
      default:
        ipv4_address: 10.0.0.3
    ports:
      - "2222:22"
      - "7071:7071"
      - "8143:143"
      - "8443:443"
      - "8993:993"
      - "9998:9998"
      - "9999:9999"
  solr:
    image: zimbra/zm-solr-docker
    container_name: solr
    env_file: .env
    networks:
      default:
        ipv4_address: 10.0.0.4
    entrypoint: /solr/entrypoint
    ports:
      - "8983:8983"
    volumes:
      - $REPO_DIR/solr:/solr

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

volumes:
  opt_zimbra: {}
