version: "3.3"

services:
  redis:
    image: library/redis
    hostname: redis
  zcs-dev:
    image: zcs-dev:latest
    build:
      context: '.'
      dockerfile: 'zcs-dev/Dockerfile'
      cache_from: [ 'zcs-dev/latest' ]
    depends_on:
      - solr
    environment:
      GITEMAIL: ${GITEMAIL}
      GITNAME: "${GITNAME}"
      SOLR_MODE: ${SOLR_MODE}
      SOLR_MEMORY: ${SOLR_MEMORY}
    entrypoint:
      - /zimbra/init
    volumes:
      - $REPO_DIR/slash-zimbra:/zimbra
      - $HOME_ZIMBRA:/home/zimbra:delegated
      - type: volume
        source: opt_zimbra
        target: /opt/zimbra
        volume:
          nocopy: false
    hostname: zcs-dev
    ports:
      - "2222:22"
      - "7071:7071"
      - "8143:143"
      - "8443:443"
      - "8993:993"
      - "9998:9998"
      - "9999:9999"
  solr:
    image: zcs-solr:latest
    build:
      context: '.'
      dockerfile: 'solr/Dockerfile'
      cache_from: [ 'zcs-solr/latest' ]
    environment:
      SOLR_MODE: ${SOLR_MODE}
      SOLR_MEMORY: ${SOLR_MEMORY}
    ports:
      - "8983:8983"
    volumes:
      - $REPO_DIR/solr:/solr
      - idxvolume:/opt/solr/server/solr
  test:
    image: zcs-test:latest
    hostname: test
    build:
      context: '.'
      dockerfile: 'test/Dockerfile'
      cache_from: [ 'zcs-test/latest' ]
    depends_on:
      - zcs-dev
    entrypoint:
      - /zimbra/init
      - --shutdown
      - "no"
    environment:
      ADMIN_PORT: "7071"
      HTTPS_PORT: "443"
      SOAPSERVICE_PORT: "8443"
      

volumes:
  opt_zimbra: {}
  idxvolume: {}
